In [53]:
import os
import json
import pandas as pd
import psycopg2

In [33]:
agg_ins_path="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/aggregated/insurance/country/india/state/"
agg_ins_list=os.listdir(agg_ins_path)

agg_ins_columns={"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }
for state in agg_ins_list:
    cur_states=agg_ins_path+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,'r')

            ag_ins_data=json.load(data)
            try:
                for i in ag_ins_data["data"]["transactionData"]:
                    name = i["name"]
                    count = i["paymentInstruments"][0]["count"]
                    amount = i["paymentInstruments"][0]["amount"]
                    agg_ins_columns["Insurance_type"].append(name)
                    agg_ins_columns["Insurance_count"].append(count)
                    agg_ins_columns["Insurance_amount"].append(amount)
                    agg_ins_columns["States"].append(state)
                    agg_ins_columns["Years"].append(year)
                    agg_ins_columns["Quarter"].append(int(file.strip(".json")))
            except:
                pass
aggre_insurance_datas = pd.DataFrame(agg_ins_columns)

In [29]:
map_insure_path="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/map/insurance/hover/country/india/state/"
map_insur_list= os.listdir(map_insure_path)

map_insure_columns= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =map_insure_path+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                map_insure_columns["Districts"].append(name)
                map_insure_columns["Transaction_count"].append(count)
                map_insure_columns["Transaction_amount"].append(amount)
                map_insure_columns["States"].append(state)
                map_insure_columns["Years"].append(year)
                map_insure_columns["Quarter"].append(int(file.strip(".json")))


map_insurance_datas = pd.DataFrame(map_insure_columns)

In [34]:
top_ins_path="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/top/insurance/country/india/state/"
top_insur_list = os.listdir(top_ins_path)

top_ins_columns = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = top_ins_path+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                top_ins_columns["Pincodes"].append(entityName)
                top_ins_columns["Transaction_count"].append(count)
                top_ins_columns["Transaction_amount"].append(amount)
                top_ins_columns["States"].append(state)
                top_ins_columns["Years"].append(year)
                top_ins_columns["Quarter"].append(int(file.strip(".json")))

top_insur_datas = pd.DataFrame(top_ins_columns)

In [30]:
#agg transaction
path1="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list=os.listdir(path1)

agg_trans_columns={'states':[],"years":[],"quater":[],"transaction_type":[],"transaction_count":[],"transaction_amount":[]}
for state in agg_trans_list:
    cur_states=path1+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,'r')

            A=json.load(data)
            for i in A['data']['transactionData']:
                name=i['name']
                count=i['paymentInstruments'][0]["count"]
                amount=i['paymentInstruments'][0]["amount"]
                agg_trans_columns["transaction_type"].append(name)
                agg_trans_columns["transaction_count"].append(count)
                agg_trans_columns["transaction_amount"].append(amount)
                agg_trans_columns["states"].append(state)
                agg_trans_columns["years"].append(year)
                agg_trans_columns["quater"].append(int(file.strip('.json')))

agg_trans_datas=pd.DataFrame(agg_trans_columns)

In [31]:
user="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/aggregated/user/country/india/state/"
agg_user_list=os.listdir(user)
agg_user_column={'states':[],"years":[],"quater":[],"brands":[],"transaction_count":[],"percentage":[]}

for state in agg_user_list:
    cur_states=user+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,'r')

            user_data=json.load(data)
            try:
                for i in user_data['data']['usersByDevice']:
                    brand=i["brand"]
                    count=i["count"]
                    percentage=i["percentage"]
                    agg_user_column["brands"].append(brand)
                    agg_user_column["transaction_count"].append(count)
                    agg_user_column["percentage"].append(percentage)
                    agg_user_column["states"].append(state)
                    agg_user_column["years"].append(year)
                    agg_user_column["quater"].append(int(file.strip('.json')))
            except:
                pass
agg_user_datas=pd.DataFrame(agg_user_column)

In [13]:
#map_transaction details
map_path_trans="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/map/transaction/hover/country/india/state/"
map_trans_list=os.listdir(map_path_trans)
map_trans_column={'states':[],"years":[],"quater":[],"name":[],"transaction_count":[],"transaction_amount":[]}
for state in map_trans_list:
    cur_state=map_path_trans+state+"/"
    map_trans_years=os.listdir(cur_state) 
    for year in map_trans_years:
        cur_year=cur_state+year+"/"
        map_file=os.listdir(cur_year)
        for file in map_file:
            cur_file=cur_year+file
            map_trans_data=open(cur_file,"r")

            map_trans_datas=json.load(map_trans_data)
            try:
                for i in map_trans_datas["data"]["hoverDataList"]:
                    name=i["name"]
                    count=i['metric'][0]['count']
                    amount=i['metric'][0]['amount']
                    map_trans_column["name"].append(name)
                    map_trans_column["transaction_count"].append(count)
                    map_trans_column["transaction_amount"].append(amount)
                    map_trans_column["states"].append(state)
                    map_trans_column["years"].append(year)
                    map_trans_column["quater"].append(int(file.strip('.json')))
            except:
                pass
map_trans_data=pd.DataFrame(map_trans_column)

In [14]:
map_path_user="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/map/user/hover/country/india/state/"
map_user_list=os.listdir(map_path_user)
map_user_column={'states':[],"years":[],"quater":[],"districs":[],"registeredUsers":[],"appOpens":[]}
for state in map_user_list:
    cur_state=map_path_user+state+"/"
    map_user_years=os.listdir(cur_state) 
    for year in map_user_years:
        cur_year=cur_state+year+"/"
        map_file=os.listdir(cur_year)
        for file in map_file:
            cur_file=cur_year+file
            map_user_data=open(cur_file,"r")
            map_user_datas=json.load(map_user_data)
            try:
                for i in map_user_datas['data']['hoverData'].items():
                    d_name=i[0]
                    registeredUsers=i[1]["registeredUsers"]
                    appOpens=i[1]["appOpens"]
                    map_user_column['states'].append(state)
                    map_user_column['years'].append(year)
                    map_user_column['districs'].append(d_name)
                    map_user_column['registeredUsers'].append(registeredUsers)
                    map_user_column['appOpens'].append(appOpens)
                    map_user_column['quater'].append(int(file.strip('.json')))
            except:
                pass
map_user_datas=pd.DataFrame(map_user_column)

In [15]:
top_path_user="C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/top/user/country/india/state/"
top_user_list=os.listdir(top_path_user)
top_user_column={'states':[],"years":[],"quater":[],"Pincodes":[],"RegisteredUser":[]}
for state in top_user_list:
    cur_state=top_path_user+state+"/"
    top_user_years=os.listdir(cur_state) 
    for year in top_user_years:
        cur_year=cur_state+year+"/"
        top_file=os.listdir(cur_year)
        for file in top_file:
            cur_file=cur_year+file
            top_user_data=open(cur_file,"r")
            top_user_datas=json.load(top_user_data)

        try:
            for i in top_user_datas["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                top_user_column["Pincodes"].append(name)
                top_user_column["RegisteredUser"].append(registeredusers)
                top_user_column["states"].append(state)
                top_user_column["years"].append(year)
                top_user_column["quater"].append(int(file.strip(".json")))
        except:
            pass
top_user_datas=pd.DataFrame(top_user_column)

In [32]:
top_tarans_path= "C:/Users/ASUS/Desktop/projects/phonepe/pulse/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(top_tarans_path)

top_tarans_columns = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = top_tarans_path+state+"/"
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                top_tarans_columns["Pincodes"].append(entityName)
                top_tarans_columns["Transaction_count"].append(count)
                top_tarans_columns["Transaction_amount"].append(amount)
                top_tarans_columns["States"].append(state)
                top_tarans_columns["Years"].append(year)
                top_tarans_columns["Quarter"].append(int(file.strip(".json")))

top_trans_datas = pd.DataFrame(top_tarans_columns)

In [25]:
mydb = psycopg2.connect(host = "localhost",
                        user = "postgres",
                        password = "varman8448",
                        database = "phonepe",
                        port = "5432"
                        )
cursor = mydb.cursor()

In [26]:
agg_ins_table= '''CREATE TABLE if not exists aggregated_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Insurance_type varchar(50),
                                                                      Insurance_count bigint,
                                                                      Insurance_amount bigint
                                                                      )'''
cursor.execute(agg_ins_table)
mydb.commit()
for index,row in aggre_insurance_datas.iterrows():
    insert_query7 = '''INSERT INTO aggregated_insurance (States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Insurance_type"],
              row["Insurance_count"],
              row["Insurance_amount"]
              )
    cursor.execute(insert_query7,values)
    mydb.commit()

In [38]:
agg_trans_table = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(agg_trans_table)
mydb.commit()

for index,row in agg_trans_datas.iterrows():
    insert_query1 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["states"],
              row["years"],
              row["quater"],
              row["transaction_type"],
              row["transaction_count"],
              row["transaction_amount"]
              )
    cursor.execute(insert_query1,values)
    mydb.commit()

In [41]:
agg_user_table = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
cursor.execute(agg_user_table)
mydb.commit()

for index,row in agg_user_datas.iterrows():
    insert_query2 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["states"],
              row["years"],
              row["quater"],
              row["brands"],
              row["transaction_count"],
              row["percentage"])
    cursor.execute(insert_query2,values)
    mydb.commit()

In [43]:
map_insurance_table = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(map_insurance_table)
mydb.commit()

for index,row in map_insurance_datas.iterrows():
            insert_query8 = '''
                INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['Districts'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query8,values)
            mydb.commit()

In [45]:
map_trans_table = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(map_trans_table)
mydb.commit()

for index,row in map_trans_data.iterrows():
            insert_query3 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['states'],
                row['years'],
                row['quater'],
                row['name'],
                row['transaction_count'],
                row['transaction_amount']
            )
            cursor.execute(insert_query3,values)
            mydb.commit()

In [49]:
map_user_table = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
cursor.execute(map_user_table)
mydb.commit()

for index,row in map_user_datas.iterrows():
    insert_query4 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["states"],
              row["years"],
              row["quater"],
              row["districs"],
              row["registeredUsers"],
              row["appOpens"])
    cursor.execute(insert_query4,values)
    mydb.commit()

In [50]:
top_insur_table= '''CREATE TABLE if not exists top_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(top_insur_table)
mydb.commit()

for index,row in top_insur_datas.iterrows():
    insert_query9 = '''INSERT INTO top_insurance (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query9,values)
    mydb.commit()

In [51]:
top_trans_table = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(top_trans_table)
mydb.commit()

for index,row in top_trans_datas.iterrows():
    insert_query5 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query5,values)
    mydb.commit()

In [52]:
top_user__table = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(top_user__table)
mydb.commit()

for index,row in top_user_datas.iterrows():
    insert_query6 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["states"],
              row["years"],
              row["quater"],
              row["Pincodes"],
              row["RegisteredUser"])
    cursor.execute(insert_query6,values)
    mydb.commit()